version: '3.8'

services:
  # SOA Bus
  soa-bus:
    build:
      context: .
      dockerfile: soa_bus/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - soa-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    ports:
      - "8010:8010"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Message Service  
  message-service:
    build:
      context: .
      dockerfile: message_service/Dockerfile
    ports:
      - "8008:8008"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Forum Service
  forum-service:
    build:
      context: .
      dockerfile: forum_service/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Post Service
  post-service:
    build:
      context: .
      dockerfile: post_service/Dockerfile
    ports:
      - "8005:8005"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Comment Service
  comment-service:
    build:
      context: .
      dockerfile: comment_service/Dockerfile
    ports:
      - "8006:8006"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Event Service
  event-service:
    build:
      context: .
      dockerfile: event_service/Dockerfile
    ports:
      - "8007:8007"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Report Service
  report-service:
    build:
      context: .
      dockerfile: report_service/Dockerfile
    ports:
      - "8009:8009"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  # Profile Service
  profile-service:
    build:
      context: .
      dockerfile: prof_service/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - soa-network
    environment:
      - SOA_SERVER_HOST=soa-bus
      - SOA_SERVER_PORT=8000
    depends_on:
      - soa-bus

  gateway:
    build:
      context: ./gateway
    ports:
      - "3001:3001"
    networks:
      - soa-network
    depends_on:
      - soa-bus
    volumes:
      - ./gateway:/app

  frontend:
    build:
      context: ./FRONTEND-nuevo
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND-nuevo:/app
      - /app/node_modules
    networks:
      - soa-network
    depends_on:
      - gateway  


networks:
  soa-network:
    driver: bridge 